{% set name = "libgcrypt" %}
{% set version = "1.8.3" %}
{% set sha256 = "66ec90be036747602f2b48f98312361a9180c97c68a690a5f376fa0f67d0af7c" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://gnupg.org/ftp/gcrypt/libgcrypt/{{ name }}-{{ version }}.tar.bz2
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True  # [win]
  run_exports:
   - {{ pin_subpackage('libgcrypt') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - libgpg-error

test:
  commands:
    - test -f $PREFIX/lib/libgcrypt.so  # [linux]
    - conda inspect linkages {{ name }}
    - conda inspect objects {{ name }}  # [osx]

about:
  home: https://gnupg.org/software/index.html
  license: GPL-2.0
  license_family: GPL
  summary: 'a general purpose cryptographic library originally based on code from GnuPG.'

extra:
  recipe-maintainers:
    - martindurant
    - mariusvniekerk
