{% set version = "1.10.1" %}

package:
  name: libgcrypt
  version: {{ version }}

source:
  url: https://gnupg.org/ftp/gcrypt/libgcrypt/libgcrypt-{{ version }}.tar.bz2
  sha256: ef14ae546b0084cd84259f61a55e07a38c3b53afc0f546bffcef2f01baffe9de

build:
  number: 0
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage('libgcrypt') }}

requirements:
  build:
    - gnuconfig  # [unix]
    - {{ compiler('c') }}
    - make
    - libgpg-error
  host:
    - libgpg-error

test:
  commands:
    - test -f ${PREFIX}/lib/libgcrypt${SHLIB_EXT}  # [linux]

about:
  home: https://gnupg.org/software/index.html
  license: LGPL-2.1-or-later AND GPL-2.0-or-later
  license_file:
    - COPYING.LIB
    - COPYING
    - LICENSES
  license_family: GPL
  summary: a general purpose cryptographic library originally based on code from GnuPG.

extra:
  recipe-maintainers:
    - martindurant
    - mariusvniekerk
    - mbargull
    - xhochy
