travis:
  secure:
    BINSTAR_TOKEN: i7mvf1re1BXQ9ZCD96C+ca2XL3/fISDNkYxvmpxBlMbEhCOj6MeLLHlxqHD2fAkWHH+CVoCO9I+ZSaVxW5YvgZPzvCH2qEZe0d98EzpLqVV89gSvnB82mCyrqQqw8SumQM5uz8sfHr1E7wZmgx2c+W/IZGvlRxnjGGD5QKTfWf5AuO4L0OQNrTYK0a3D+THznqNKMFom4qMbfVaNk+jSkXZEYpi66sjRaQ8ej6f128hK0n5iTMm4XzewpGe8z+7fmJYL1DBgSUHtslZP7jPW/qsRXQMUaqi9NVCeh1sQEoePS0G2SHd4TD479KyFcUDaoi0S4mrOo1AY7U3USWon0kEh9SEhzfVMIQLSBQ0TbB7VNKJTALs+3T7SyLFzbrb+Klmyn6SB5Ptahzj+X7JhRsu2sVOEs43fUqA1ozxtZMa6T0M6LQi5xqfoQ57kh9SdxYcDIPWR51c7mA5uPeX/+MBY2Zx/4QWBBr1S/x4lztFhdCezdsrN/7/g/LfsWBfZnvNKrVoEnrhT/AtN3lM1+0pWOqmlvV5vL4SfT0ZuDM/GlauYOuw6efSdItynOK5sQnnqZbwjZUtuW+nTjFjSH1UvYpZ/2Ps7ojMSBeuZykj4M3aYrH66J3nzjqCo2lL9+6/8L0YDyl2Ifhm2YzxDr+luxeBjADmJf3zayfIPSjA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
